In [6]:
import subprocess
import sys

# 1. Colocamos apenas os pacotes externos em uma lista
pacotes = ["pandas", "numpy", "matplotlib", "seaborn"]

print("Verificando as bibliotecas necessárias...\n")

# 2. O laço 'for' vai passar por cada pacote da lista
for pacote in pacotes:
    try:
        # Tenta importar o pacote pelo nome (usando uma função especial para textos)
        __import__(pacote)
        print(f"✅ {pacote} já estava instalado.")
        
    except ImportError:
        # Se der erro, instala automaticamente
        print(f"⏳ {pacote} não encontrado. Instalando agora...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", pacote])
        print(f"✅ {pacote} instalado com sucesso!")

print("\nTodas as dependências estão prontas!")

# 3. Agora importamos todas elas com seus apelidos clássicos para usar no código, incluindo o random
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random

# Importa o warnings e pedimos para ignorar os avisos visuais
import warnings
warnings.filterwarnings('ignore')

Verificando as bibliotecas necessárias...

✅ pandas já estava instalado.
✅ numpy já estava instalado.
✅ matplotlib já estava instalado.
✅ seaborn já estava instalado.

Todas as dependências estão prontas!

# Leitura do arquivo

Carregamento do Dataset do instagram.

- Os dados foram retirados da plataforma  Kaggle.

In [7]:
# Leitura dos dados do arquivo Instagram_Analytics.csv

df = pd.read_csv ("Instagram_Analytics.csv")
df.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,...,5,7,34,4327,6230,0.0385,899,100,7,medium
1,IG0000002,20,creator,31095,image,Fitness,Hashtags,1,2025-08-15 15:00:00,2025-08-15,...,10,21,68,7451,8268,0.0663,805,122,5,viral
2,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,...,2,1,22,1639,2616,0.0531,758,115,8,high
3,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,...,0,7,0,2877,3171,0.0309,402,115,7,medium
4,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,...,8,5,21,5350,8503,0.0221,155,112,9,low

In [8]:
# Informações sobre a tabela

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   post_id                   29999 non-null  object
 1   account_id                29999 non-null  int64
 2   account_type              29999 non-null  object
 3   follower_count            29999 non-null  int64
 4   media_type                29999 non-null  object
 5   content_category          29999 non-null  object
 6   traffic_source            29999 non-null  object
 7   has_call_to_action        29999 non-null  int64
 8   post_datetime             29999 non-null  object
 9   post_date                 29999 non-null  object
 10  post_hour                 29999 non-null  int64
 11  day_of_week               29999 non-null  object
 12  likes                     29999 non-null  int64
 13  comments                  29999 non-null  int64
 14  shares                    29999 non-null  int64
 15  saves                     29999 non-null  int64
 16  reach                     29999 non-null  int64
 17  impressions               29999 non-null  int64
 18  engagement_rate           29999 non-null  float64
 19  followers_gained          29999 non-null  int64
 20  caption_length            29999 non-null  int64
 21  hashtags_count            29999 non-null  int64
 22  performance_bucket_label  29999 non-null  object
dtypes: float64(1), int64(13), object(9)
memory usage: 5.3+ MB

- A tabela não apresenta valores ausentes.
- A tabela apresenta o Dtype corretamente distribuído.

## Verificando a coluna "content_category"

Identificar as categorias para verificar quais nichos a agência de marketing terá em mãos para trabalhar.

In [9]:
# Quantidade de postagem para cada categoria.

df['content_category'].value_counts()

content_category
Photography    3035
Fashion        3034
Technology     3025
Lifestyle      3017
Food           3010
Fitness        3004
Music          3003
Travel         2968
Beauty         2953
Comedy         2950
Name: count, dtype: int64

- A base de dados está bem balanceada, ou seja, nenhuma categoria terá vantagens por ter mais dados.

## Qual dessas categorias tem o melhor desempenho?

Para está pergunta vamos utilizar o recurso groupby, e calcular a média de engajamento e curtidas de cada categoria.

In [17]:
# Agrupando as categorias rate e likes

desempenho_categorias = df.groupby('content_category')[['engagement_rate','likes']].mean()

# Ordenar a tabela, para mostrar as maiores taxas

desempenho_categorias = desempenho_categorias.sort_values(by='engagement_rate', ascending=False)

# exibir o resultado

desempenho_categorias

                  engagement_rate       likes
content_category
Music                    0.042808  292.132867
Fitness                  0.042720  289.139481
Fashion                  0.042615  296.815425
Beauty                   0.042197  288.440230
Food                     0.042078  287.629900
Technology               0.042023  277.763967
Comedy                   0.041854  289.001356
Travel                   0.041677  279.374663
Lifestyle                0.041646  285.744448
Photography              0.041452  290.391104

- Podemos observar que Music, fitness e Fashion geram mais interações atualmente no instagram.